name: choco
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          scripts/mkchoco.bat

      - name: Archive Package
        uses: actions/upload-artifact@v2
        with:
          name: nvml-exporter-nupkg
          path: |
            packaging/choco/nvml-exporter/nvml-exporter*.nupkg

      - name: Push Package
        if: ${{ github.event_name == 'release_noexist' }}
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          cd packaging/choco/nvml-exporter
          choco push --api-key $env:CHOCO_API_KEY $(gci nvml-exporter*.nupkg).name --source https://push.chocolatey.org/